name: Python Setup
description: Set up Python environment and install requirements

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.5"

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      shell: bash
